<?php
/**
 * Created by PhpStorm.
 * User: Роман
 * Date: 25.06.2016
 * Time: 1:45
 */

namespace BotTelegram\Validators;

use Illuminate\Validation\Validator;

class BotValidator extends Validator {

//    public function validator(\Illuminate\Validation\Factory $factory)
//    {
//
//        Validator::extend('eachFile', function($attribute, $value, $parameters) {
//            foreach ( $value as $key => $image ) // add individual rules to each image
//            {
//                $this->messages[sprintf( 'files.%d', $key )] = 'Неверный тип файла должен быть '.implode(",", $parameters);
//                $result = $this->validateMimes(sprintf( 'files.%d', $key ), $image, $parameters);
//            }
//            return $result;
//        });
//
//        $validator = $factory->make(
//            $this->all(), $this->container->call([$this, 'rules']), $this->messages(), $this->attributes()
//        );
//
//        return $validator;
//    }

    public function validateEachFile($attribute, $value, $parameters) {

        $this->setCustomMessages(['each_file' => 'Неверный тип файла :variable должен быть '.implode(",", $parameters)]);
        foreach ( $value as $key => $image ) // add individual rules to each image
        {
            $result = $this->validateMimes(sprintf( 'files.%d', $key ), $image, $parameters);
        }
        return $result;
    }

    public function messages()
    {

        return parent::messages(); // TODO: Change the autogenerated stub
    }

}